### ISSUE TITLE
Multi Currencies

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#198]
https://usabilitydynamics.uservoice.com/admin/forums/95259-wp-property

**Comment by gprofitos** [comment]
Hello, is multi currencies something you plan to implement? Because there are quite a few countries where you need to use two currencies for Real Estate, so Real Estate sites for those countries give users the chance to filter with one currency or the other. Or when submiting a property, they can choose between doing it with X or with Y currency. Otherwise, in search results they found propertis with both currencies, because the search results are ordered using exchange rates. In this moment there are no other WP theme or plugin with multi-currencie support. Thank you

**Comment by ewsopp** [comment]
@Naide please submit your ideas and vote on other ideas at http://feedback.usabilitydynamics.com/forums/95259-wp-property

We look to the above website for direction on what to develop next. Thanks for your support. :-)

**Comment by gprofitos** [comment]
Thank you awsopp. I just did it.
