### ISSUE TITLE
add support for default attribute values

### ISSUE THREAD

**Issue by ewsopp** [wp-property/wp-property#203]
For an attribute, provide support for a default value. This default value should be applied to existing listings and all future listings.

For the interface, here is one possible solution...

![image](https://cloud.githubusercontent.com/assets/5578537/11565372/c49ee184-99ab-11e5-97d4-87e1a3724f22.png)

**Comment by ewsopp** [comment]
When setting the new default value, we should not overwrite any existing value that may be stored on that same attribute for existing listings.

**Comment by alimuzzaman** [comment]
Currently I have no idea how this can be on existing listings.
I mean how can I decide whether to apply defaults on existing listings or not?

**Comment by pemaxim** [comment]
@ewsopp I believe, different issues can be occurred on trying to implement the feature.

##### UI

I think we already have a bit overloaded UI for Attribute management. Probably, we should re-design Attribute Row UI for adding ability to add new features in relevant places.
I'm not sure, that's adding default field under 'Data Entry' is good idea. We already have textarea for dropdown list and multiple values under data entry type. So, it may be confusing for user to have one more field there. Especially, if fields will not have labels.

##### Applying default value.

By default, default value must be used on creating new property.
But, we must not to apply default value to existing property by default too.
Because, any 'non-familiar' user may break all their properties by providing default value to some specific attribute accidently. For example, price.

Instead, we should add 'Apply to All' button. On click it should send AJAX request to server to determine if we already store any value for this attribute. And, if any property already has the value for this attribute, we show Confirmation Modal Window on response. Something like "You are already using this attribute for your properties.  Attention, attribute's value will be overwritten for all your properties! Are you sure you want to continue?" On confirmation, we are doing another ajax request, which creates default value or replaces the old value with provided one for all existing properties.

##### Relation to Data Entry

We must not show default value for specific data entry types, such as:
- Image Upload
- File Upload

Also, we may have issues with the following data entry types:

###### Single Checkbox

I believe we should show another option instead of default value field for this attribute.
Something like checkbox 'Check by default'. Or dropdown list: 'checked', 'unchecked'.

###### Color picker

We should show Color Picker instead of text input field.

###### Date and Time pickers.

We should show Date and/or Time Picker instead of text input field. 

###### Dropdown, Advanced Dropdown, Multi-Checkbox

We should show dropdown list with predefined values ( see: http://screencast.com/t/btdLXoHQL7G ) to prevent conflict in case, when not defined value may be used.

**Comment by pemaxim** [comment]
@ewsopp Also, probably, it would be better to implement the feature as separate Add-on?

**Comment by pemaxim** [comment]
@alimuzzaman hold on with the issue, for now, please.

**Comment by ewsopp** [comment]
In terms of UI, I agree the UI is getting busy. One way to keep it clear would be to only display the additional 'default value' field when the 'enable default value' checkbox is enabled. It should have a label too. Thoughts on that?

I agree that we need to be careful about applying the default value to existing listings. We don't want to overwrite anything, unless the user specifically wants to do this via a separate action (clicking an apply button or something else - maybe even adding a 2nd confirmation via Nonces).

Maybe we provide a few options for applying the new value
1 - only apply to new listings.
2 - apply to new listings AND apply to listings that have no value for this field.
3 - apply to new listings AND overwrite current value in all listings.

**Comment by Mashenka** [comment]
@ewsopp also if we need this task for rdc, probably will be easier to write simple script to update particular attributes. This will take much less time.

**Comment by ewsopp** [comment]
The feature has been requested by others as well. See http://feedback.usabilitydynamics.com/forums/95259-wp-property/suggestions/10686735-default-value

**Comment by ewsopp** [comment]
@Mashenka this is not just about RDC. It is also about product improvement. Creating new features for our user base.

**Comment by Mashenka** [comment]
Some thoughts.

We already have default attribute Phone Number in Settings/Main tab, so we can just add ability for users to new default attributes there:

![image](https://cloud.githubusercontent.com/assets/5111163/11712489/8fb0c846-9f3e-11e5-891e-327ea4de20c8.png)

**Comment by pemaxim** [comment]
@alimuzzaman 

Look through my and @ewsopp comments:
- https://github.com/wp-property/wp-property/issues/203#issuecomment-162534191
- https://github.com/wp-property/wp-property/issues/203#issuecomment-162541533

Here is some objectives and updates to written above:
- [x] Set schema for acceptable 'default values' ( e.g., like searchable attribute types: http://screencast.com/t/XdhgMail ). The following attributes acceptable: `Free Text`, `Textarea`, `Text Editor`, `Number`, `Currency`, `URL`, `Oembed`. Schema should include field type which should be rendered for default value. For example: `input` ( text field ) should be rendered for `Number`; `textarea` should be rendered for `Text Editor`.
- [x] Show 'Enable default value assign.' option only if the attribute type matches schema.
- [x] Show 'Default Value' field only when 'Enable default value assign.' options is checked.
- [x] Add Label 'Default Value' for default value field.
- [x] Add 'Apply to All' button. See my comments about this button above.

Please, continue to work on the issue.
Let me know if you have any questions.

**Comment by Mashenka** [comment]
@alimuzzaman did you finish this task?

**Comment by alimuzzaman** [comment]
Yes. Please check

**Comment by Mashenka** [comment]
- [x] There is an issue on workspace when I try to edit or add property
  http://workspace.uds.io/wp-admin/post-new.php?post_type=property#
- [x] When I click option "Enable default value assign" there is no box to do that, only when I resave page with that option enabled.
  ![image](https://cloud.githubusercontent.com/assets/5111163/12003163/712e030a-ab25-11e5-972d-1a379d2a0097.png)

**Comment by Mashenka** [comment]
- [x] change "for this field" to "for this data entry type"
- [x] make info box not moving near the kursor
  ![image](https://cloud.githubusercontent.com/assets/5111163/12019581/00be84e0-ad83-11e5-8f6f-a1d53749b716.png)

**Comment by alimuzzaman** [comment]
I think it's will be easy for who developed that feature. I think this bug is related to toltip.

**Comment by Mashenka** [comment]
and who developed that featurte? I think you added it.

**Comment by alimuzzaman** [comment]
I just added the title tag. On setting page title converted to toltip. 
@pemaxim can you help on this?

**Comment by pemaxim** [comment]
@alimuzzaman be careful on copying any stuff. 
- [x] Fix: You created a function and added korotkov@UD as author and since 1.36.2, however next version will be 2.1.5 : https://github.com/wp-property/wp-property/commit/b553d0138a63c996eca86a414ccc9f5b6d3affe0#diff-13d43b4b5ea854e4c6685f0a53ddd50fR4734

Also, do not add functions ‘class' file.  It’s bad practice. We use autoload for classes, but not for functions.
Add static method to WPP_F class instead. Honestly, other function under WPP_F class should be moved to class methods too.
- [x] Fix: Check `wpp_apply_default_value()` function. You are using default strings but you must always use L10n functions. See: https://codex.wordpress.org/L10n

Also, regarding ‘Property’ and ‘Properties’ values in context. We have ‘White Label’ functionality for it ( WP-Property: Power Tools Add-ons ). So user has ability to replace ‘Property’ and ‘Properties’ with any other value. 
- [x] Fix: So, be sure, you are always using `WPP_F::property_label()`

Example:
`sprintf( __( "Key already exist ( In %d  %s ). Do you want to replace?", ud_get_wp_property()->domain ), $count, WPP_F::property_label( 'plural' ) );`

**Comment by pemaxim** [comment]
- [x] Fix: https://github.com/wp-property/wp-property/commit/b553d0138a63c996eca86a414ccc9f5b6d3affe0#commitcomment-15203157

**Comment by pemaxim** [comment]
- [ ] Fix: https://github.com/wp-property/wp-property/commit/749bd6c9dc36ff11c8f083345411dc58a0dc0e56#commitcomment-15203367

**Comment by Mashenka** [comment]
@alimuzzaman Change the text in the info box
![image](https://cloud.githubusercontent.com/assets/5111163/12050234/dded8656-af02-11e5-845f-fca9a21a141f.png)

Attribute value already exist in 15 properties(if singular 1 property). Do you want to replace those(that) values(value)?

Regarding buttons,change:
Yes ALL -> Replace all 
Empty or not exist - > Replace only empty

**Comment by ewsopp** [comment]
- [ ] When hover over the 'Enable default value assign.' option, a tooltip message appears new my mouse and does not disappear. 

![image](https://cloud.githubusercontent.com/assets/5578537/12076045/36d35a22-b168-11e5-986f-1373d5aab836.png)

**Comment by alimuzzaman** [comment]
https://github.com/wp-property/wp-property/blob/latest/static/scripts/wpp.admin.settings.js#L538

**Comment by alimuzzaman** [comment]
please review this.

**Comment by Mashenka** [comment]
ok. need some time

**Comment by Mashenka** [comment]
Doesn't work on workspace neither when creating new attribute or for old one. Button apply doesn't work

**Comment by alimuzzaman** [comment]
@Mashenka It's working now.

**Comment by Mashenka** [comment]
no, it is not working. Are you checking on workspace before writing here?
![image](https://cloud.githubusercontent.com/assets/5111163/12486455/dfb626e6-c073-11e5-90c5-c5d68ae3cad8.png)

**Comment by pemaxim** [comment]
@alimuzzaman @Mashenka What is the status?

**Comment by alimuzzaman** [comment]
Working...

**Comment by pemaxim** [comment]
![image](https://cloud.githubusercontent.com/assets/308489/12717984/339e88e2-c8f4-11e5-8038-9d8ccf9a9b14.png)

@alimuzzaman  Look through the comment: https://github.com/wp-property/wp-property/issues/203#issuecomment-167984782

> Attribute value already exist in 15 properties (if singular 1 property). Do you want to replace those(that) values(value)?

**Comment by Mashenka** [comment]
Odd word and plural
![image](https://cloud.githubusercontent.com/assets/5111163/12718193/e56d2b6a-c8fd-11e5-85ae-69eca2a0c387.png)

**Comment by pemaxim** [comment]
![image](https://cloud.githubusercontent.com/assets/308489/12718137/1e35299c-c8f5-11e5-8c88-46f043d8bad0.png)

**Comment by Mashenka** [comment]
L10 function doesn't exist for this string
![image](https://cloud.githubusercontent.com/assets/5111163/12718316/e89a891c-c8fe-11e5-910a-70cd91a3831a.png)

**Comment by Mashenka** [comment]
The same as for these lines (no L10 function)
![image](https://cloud.githubusercontent.com/assets/5111163/12718369/4ada3c80-c8ff-11e5-9105-c60c7e44080e.png)
Also buttons are not translatable and "are you sure?"
![image](https://cloud.githubusercontent.com/assets/5111163/12718602/aa1b07e6-c900-11e5-87ae-02579ebe0968.png)

**Comment by Mashenka** [comment]
Ok, the following lines are still not translatable:
- [x] - Enable default value assign 
  - [x]  - Are you sure?  // js 
- [x] - Done! // js 
  - [x]  - Cancel // js
- [x] - Replace all // js exist in the list of strings but not translatable
- [x] - Replace only empty // js exist in the list of strings but not translatable
- [x] - Apply to all
- [x] - Apply to listing that have no value for this field  // js
- [x] - Default value
  - [x] Also https://github.com/wp-property/wp-property/issues/203#issuecomment-167984782 still not changed

**Comment by Mashenka** [comment]
- [x] 
  ![image](https://cloud.githubusercontent.com/assets/5111163/12787429/74abff0a-caa6-11e5-9dfd-6827d33767cd.png)

**Comment by pemaxim** [comment]
@Mashenka @alimuzzaman 

Regarding `undefined` values and any other ones. Some functionality is being implemented via javascript. We are generating l10n cache file which is being used for localisations. So be sure when you are doing QA, that you are flushing cache on Settings -> Help tab.

![image](https://cloud.githubusercontent.com/assets/308489/12789247/b575c6d4-caa5-11e5-8ecb-f637b4693525.png)

**Comment by alimuzzaman** [comment]
@Mashenka can't find those string because Poedit exclude /static folder. where we need /static/views folder.
@pemaxim or @andypotanin can you help to exclude /static without /static/views.

**Comment by Mashenka** [comment]
Anton helped with that. There should be excluded all except view folder.
- [x] Also default value should be saved in Developer tab the same as checkbox checked after settings applied.

**Comment by alimuzzaman** [comment]
@Mashenka Please ask @pemaxim for the "cancel" isseu.

**Comment by Mashenka** [comment]
Please check string \* [ ] Done! . It is exist in the list, it is translated to Russian but not in the UI
![image](https://cloud.githubusercontent.com/assets/5111163/12842783/f7f29a30-cc05-11e5-9e4d-9a75f93e6700.png)

**Comment by alimuzzaman** [comment]
Sorry to not say that new fix is there.

**Comment by joewebdev** [comment]
I'd like to propose that you extend this ability to Dropdown Select. Is that possible?
![image](https://cloud.githubusercontent.com/assets/3836021/25601405/cee86e9a-2eb9-11e7-9ae5-5f22233eb0a8.png)

**Comment by Mashenka** [comment]
@joewebdev no, that is not possible for particular reasons.
