### ISSUE TITLE
Fatal Error on activating Meta Box plugin

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#208]
Warning: require_once(/home/eney00/rent-home.in.ua/www/wp-content/plugins/wp-property/vendor/plugins/wp-meta-box/inc/validation.php): failed to open stream: No such file or directory in /home/eney00/rent-home.in.ua/www/wp-content/plugins/meta-box/meta-box.php on line 47

Fatal error: require_once(): Failed opening required '/home/eney00/rent-home.in.ua/www/wp-content/plugins/wp-property/vendor/plugins/wp-meta-box/inc/validation.php' (include_path='.:/usr/local/pear/php54') in /home/eney00/rent-home.in.ua/www/wp-content/plugins/meta-box/meta-box.php on line 47

**Comment by pemaxim** [comment]
Updated meta-box plugin and utilities to the latest versions. Waiting next Meta Box plugin's release since the latest 4.7.3 has initialization issue which causes fatal error on trying to activate standalone meta box plugin in case it's already being used in another plugin ( WP-Property, in our case ) or Theme.

**Comment by andypotanin** [comment]
Looks like we need to change wp-meta-box to lib-meta-box and branch it away from the plugin being used as a "plugin" to being used as a composer library.

**Comment by Mashenka** [comment]
4.8.2 still have issue

**Comment by Mashenka** [comment]
4.9.8 no more
