### ISSUE TITLE
Property Type Taxonomy

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#318]
Andy added new default Taxonomy Property Type. It should add new term to Taxonomy Property type when new property types is added in Developer tab.

Issues:
* [ ] When I add new type in developer tab it doesn't saves at all, neither in developer tab nor in Property type Taxonomy. It only can be added when I'm adding it from here
![image](https://cloud.githubusercontent.com/assets/5111163/20143751/d5799fb2-a6a2-11e6-9a5a-e46f15e58322.png)

But in developer tab will appear only when I will assign at least one property to this property type.

**Comment by Mashenka** [comment]
- wpp_type taxanomy should be shown instead of  Property type attribute on edit/add property page. That will make possible to add new property type while you adding new property

**Comment by alimuzzaman** [comment]
Hide property type attribute.

**Comment by ElenaRad** [comment]
Spoke to Alim about the issues. He will  work on this today (11/15/16). He is having issues hiding the default "property type" attr.

**Comment by ElenaRad** [comment]
@alimuzzaman  checked the results, but I think there is a misunderstanding here.  What  I get now is still 2 fileds for Property type in the edit page. When I remove WP-Terms... the default property type field does not work at all. 

What is the issue?  Because of the new taxonomy/terms addition to the plug-in, we have 2 fields that are the same "Property Type", so if I go to add property and put in different values, only one of them will show up on  frontend. 

What we need: 
1. When WP-Terms is active, we need to hide  default "Property Type" attribute, so it does not show up on the Edit page. 
2. When we do not have Terms, we need the default "Property Type" attribute to function as it did.

**Comment by andypotanin** [comment]
@raj-uimatic @ElenaRad @alimuzzaman Actually we need the "Property Type" attribute enabled regardless of whether WP-Property Terms is activated or not.  Here's is a recap of what the requirement:
- The field should have always been a taxonomy, not a meta field, not we are trying to correct our mistake.
- Property Type used to be stored in `property_type` meta field. It has been this way for many years.
- Property Type is a "system field", in our case. It must always be present. Users shouldn't be able to remove it.  This needs to be kept as is since a lot of functionality expects each property to have a `property_type` meta value. 
- We now want to have Property Type to be a taxonomy and be stored as terms (`wpp_type`, specifically) but to not break lots of logic that depends on the `property_type` meta field, we want to continue using it as well. 
- However, when editing/creating properties, we only want to show one UI element for setting/changing the Property Type.
- When a property type is updated/created and a Property Type (wpp_type) is set, it needs to record the term slug into `property_type` meta field for the property object.
- If a user happens to have WP-Property Terms extension - they will be able to configure stuff like the URL rewrite slug for the `wpp_type` field, as for any other taxonomy. Having this plugin does not enable/disable the actual taxonomy.

So the simplest solution I can think of is:
1. Hide the legacy property_type field from the UI.
2. Force the new `wpp_type` UI to show up on property editor.
3. Add logic to `save_post` action (or whatever its called) to keep property_type meta field in sync with the term set when a property is updated.

**Comment by alimuzzaman** [comment]
@Mashenka @ElenaRad @andypotanin 
Is "add new property type while adding new property" must?
This feature will be available when terms plugin is active but not if inactive.
If this is must then I have to move code for taxonomy failed to wp-property from terms.

**Comment by andypotanin** [comment]
In general, we want people to be able to add terms on-the-fly while editing properties. So, yes.

**Comment by ElenaRad** [comment]
Since we have decided to combine Terms and WPP, we will need to visually hide Property Type attribute:
![image](https://cloud.githubusercontent.com/assets/19193013/20434349/18d09a5e-adb0-11e6-9231-dbab20a7faa2.png)

The Term field will remain on Add/Edit property: 
![image](https://cloud.githubusercontent.com/assets/19193013/20434391/3f2785c8-adb0-11e6-9e4d-717b1978dcc8.png)

Key points:
- [x]  Get rid of Property type attribute only so it will not appear in UI and leave it as meta in the DB. 
- [x]  User can add a new type within the add/edit page. 
- [x]  Only ONE property type can be added in Edit/Add page.

**Comment by ElenaRad** [comment]
Important: 
- [x] Need to remove Meta element from Developers Tab altogether. Since these fixes are related, it can be completed together: 
  ![image](https://cloud.githubusercontent.com/assets/19193013/20438146/2c854a7c-adbf-11e6-9602-bbf5c5f32a3d.png)
