### ISSUE TITLE
conflict between attribute and term Property type when update plugin

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#390]
Steps to replicate.

1. Set up released version 2.2.0.1 and add Property Type as attribute in Developer tab. make sure that it filled in your properties. You can do that fast in Settings/Help tab by assigning one property type to all properties.

2. than update plugin wp-property from the latest branch and go to edit single property. You will see both attribute and term there. If term not filled [property_overview] won't be working
![image](https://cloud.githubusercontent.com/assets/5111163/22933878/9c9034ac-f2d5-11e6-8f6c-cb6e07e3cb8f.png)

**Comment by andypotanin** [comment]
@Mashenka We should discuss this.

**Comment by Mashenka** [comment]
There should be only one Property Type as were before on edit property page. term shouldn't be shown there.

**Comment by andypotanin** [comment]
@alimuzzaman To be clear, the standard `wpp_type` taxonomy is conflicting with the legacy `property_type` meta field, that is being rendered there as a dropdown. When saved each property should have both - a term added to the `wpp_type` taxonomy and the slug of the value stored in `property_type` meta field, for backwards compatibility. 

We need to only show one in the UI, we could probably continue using the legacy `property_type` input, which is hardcoded. 

Users shouldn't be able to add new Types from the single property editing UI, so using the term-entry UI doesn't work well. New Types are added in the Settings panel. 

Also remember that based on the Type selection, some attributes may be hidden since we allow for property-type-specific attributes to be excluded.

**Comment by alimuzzaman** [comment]
@andypotanin I have make some changes https://github.com/wp-property/wp-property/pull/392/commits/5a5c16784605681aa0f0ba7e11a4342127d51ca7. Pull request is https://github.com/wp-property/wp-property/pull/392

By the changes:
Legacy property_type input will be hidden.
The UI of taxonomy will be used.
If the property don't have wpp_type taxonomy then check for legacy property_type post meta.

**Comment by andypotanin** [comment]
@Mashenka does this work as expected?

**Comment by Mashenka** [comment]
@andypotanin no

@alimuzzaman we need to hide term and leave our old hardcoded attribute Property Type with should be always in General group

**Comment by alimuzzaman** [comment]
@Mashenka Should I disable the wpp_type (term)? Because if we hide wpp_type then it's have no use.
Although wpp_type  is backward compatible with previous version.

**Comment by Mashenka** [comment]
yes, we need to hide on edit property page. but on frontend it should be clickable as term

**Comment by alimuzzaman** [comment]
Then we must use wpp_type (term).

**Comment by Mashenka** [comment]
on frontend yes

**Comment by Mashenka** [comment]
ok, on backend everything correct, now need that it will be clickable on frontend - https://workspace.uds.io/properties/18-greentrees-road-terenure-dublin-12/

also on newly created showing as attribute - https://workspace.uds.io/properties/test/

**Comment by Mashenka** [comment]
Select property type not working - https://workspace.uds.io/wp-admin/post.php?post=749971&action=edit

![image](https://cloud.githubusercontent.com/assets/5111163/23124479/f593fcce-f775-11e6-883b-1cb7dc3a497e.png)

**Comment by Mashenka** [comment]
Ok, I saved settings and types appear in list but  now it is not selected on backend, but on frontend selected - https://workspace.uds.io/wp-admin/post.php?post=749971&action=edit

**Comment by Mashenka** [comment]
Issue appeared again on new installs 
and on old showing term on the backend, however, was discussed to show default system attribute

**Comment by pemaxim** [comment]
@Mashenka @alimuzzaman  hold on here, please. I refactored 'property type taxonomy' logic. The are a bunch of fixes/changes/improvements.
@Mashenka if you will continue to face with the issue, ask @fqjony for help. He's aware of changes.

**Comment by pemaxim** [comment]
@Mashenka @fqjony here is what was done:

## Features

* Terms are hierarchical.
* Since `property_type` can not be hierarchical, we generate `property_type` for every term. If term is child, label and slug of term will be combination of `{parent} / {child}` ( label ) and `{parent}_{child}` ( slug ).
* Our `term<->property_type` relation is stored in term's meta `property_type`.
* We set `property_type` by most direct listing type term. So, if listing belongs to `Commercial` (parent term) and to `Office` (child term), the `property_type` will be `Commercial / Office`.
* We sync the data in both directions. So: 
** If new property_type is created, - new term will be created and assigned to that property. 
** If new term is created, - we create new property_type and assign term to it.
* Exception: You can not delete property_type in WPP Settings UI. You have to remove assigned term, and property_type will be deleted. It's done to prevent conflicts.

NOTE, we can use `property_type` and `wpp_listing_type` terms for different purposes. So, if you need logic, related hierarchical structure - you should use `wpp_listing_type` term.

## CLI

To fix (update) `property_type` for all properties run:

```
wp property scroll --do-action=wpp_listing_type
```

To fix (sync) `wpp_listing_type` terms and `property_type` run:

```
wp property trigger --do-action=upgrade_property_types
```

To force:

```
wp property trigger --do-action=upgrade_property_types --force=1
```

### Screens and Examples:

![image](https://user-images.githubusercontent.com/308489/28984455-b7249b24-7966-11e7-8f51-78d1ac146634.png)


![image](https://user-images.githubusercontent.com/308489/28984496-e406705e-7966-11e7-8258-4d00c9810440.png)


![image](https://user-images.githubusercontent.com/308489/28984743-1ada7f16-7968-11e7-8547-b59b8d7f4a7a.png)


![image](https://user-images.githubusercontent.com/308489/28984581-6d386940-7967-11e7-82d9-cd11b9f4125d.png)

**Comment by Mashenka** [comment]
@fqjony @pemaxim still the issue exists https://github.com/wp-property/wp-property/issues/390#issue-207536366. On edit property page there are both term and attribute. We need to have only one on backend  - our default Property Type attribute 
and on frontend Property type term

There was already fix for that, but last commits overwrote them.
