### ISSUE TITLE
prefix slugs of newly created attributes and terms with wpp_

### ISSUE THREAD

**Issue by ewsopp** [wp-property/wp-property#391]
By default, all new attribute and term slugs should be prefixed with `wpp_`

**Comment by alimuzzaman** [comment]
@ewsopp Is there something need to do or just for information?

**Comment by Mashenka** [comment]
@alimuzzaman that need to do.

So all our default attributes and terms should have wpp_  perfix 
Also when someone adding new attribute there should be also prefix in slug

@ewsopp Did I correctly described ?

**Comment by ewsopp** [comment]
Yea - this is for the slug only. All the attributes and taxonomy slugs should be prefixed with `wpp_`.

**Comment by ewsopp** [comment]
@Mashenka is this done?

**Comment by Mashenka** [comment]
@ewsopp no

**Comment by andypotanin** [comment]
@ewsopp @Mashenka Perhaps we should wait to do this until we have new UI designs from @pareshUD? Since the UI for adding/removing attributes and fields is likely to change in near future, perhaps there's no point to adding this feature to the current Developer tab which may be depreciated altogether.

**Comment by Mashenka** [comment]
@andypotanin Agree, I do not see point at all
