### ISSUE TITLE
add support for multiple aliases to a single attribute

### ISSUE THREAD

**Issue by ewsopp** [wp-property/wp-property#416]
At the moment, I can only alias a single RETS field to a WPP attribute. We need to support the aliasing of multiple RETS fields to a single WPP attribute.

**Comment by pemaxim** [comment]
@ewsopp @andypotanin FYI, WP-Property's is designed to have attributes with ONLY single ( not multiple ) value. We had the issues in past on trying to implement multiple values for attributes and we stopped working on it because of bunch of different bugs and issues. Multiple aliases implementation is the same like have multiple values for an attribute.

**Comment by ewsopp** [comment]
For meta attributes, can we just append it to the current value following a comma?

For taxonomy attributes, is it possible?

**Comment by pemaxim** [comment]
@ewsopp 

> For meta attributes, can we just append it to the current value following a comma?

You can set via comma any amount of aliases for current attribute field. And it dos not matter what you set, - taxonomy or postmeta. 

> For taxonomy attributes, is it possible?

We decided to disable aliases for taxonomies to prevent different issues. But you can set taxonomy as aliases to attribute.

Also:

![image](https://cloud.githubusercontent.com/assets/308489/24717512/660eacbe-1a3b-11e7-93eb-98de85a917fd.png)

![image](https://cloud.githubusercontent.com/assets/308489/24717618/c2ea63f6-1a3b-11e7-802a-8b4d931778da.png)
