### ISSUE TITLE
Default Property page option in Settings/Main tab

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#543]
![image](https://user-images.githubusercontent.com/5111163/38375105-09d5e754-38fe-11e8-8af7-b1b6463571d3.png)

Was added logic than on update we are adding a new page with the name Properties and removing option Default property page in the dropdown ^

That shouldn't influence the case where already set up some another page from the site.

also for some reason was created 2 properties page.
![image](https://user-images.githubusercontent.com/5111163/38375264-7c85e416-38fe-11e8-8e00-3c3dafe3a15a.png)

**Comment by ewsopp** [comment]
@fqjony and I have experienced the Properties page being duplicated numerous times. Check with him for some feedback.

**Comment by fqjony** [comment]
@Mashenka @SoSeductive yeah, let me describe it

When we try to set page as `Properties page` with some slug different than `properties`, `listing` in rdc's case, one more page with `properties` slug is dynamically creating and coming as `Properties page` instead of page which was set earlier.

* Wanted page 

![image](https://user-images.githubusercontent.com/12067297/38384635-5a2ebd88-3918-11e8-8f0e-78a833be554f.png)

* There is 2 pages (one is created by user, another dynamically)

![image](https://user-images.githubusercontent.com/12067297/38384668-6a86b1c2-3918-11e8-9751-1a4420c9a024.png)

* Page which was set by user as `Properties page`

![image](https://user-images.githubusercontent.com/12067297/38384701-88948be4-3918-11e8-8b05-e100c928b137.png)

* Then I go to Pages and try to remove no needed page with `properties` slug and I seeing situation provided bellow. One more page auto created and set as `Properties page`

![image](https://user-images.githubusercontent.com/12067297/38384754-a09fcff0-3918-11e8-99ba-50c7a4f69901.png)

![image](https://user-images.githubusercontent.com/12067297/38384842-de48d9fa-3918-11e8-9634-56b7337cfc99.png)

Let me know if you have more questions.

**Comment by SoSeductive** [comment]
@Mashenka Done

**Comment by SoSeductive** [comment]
@Mashenka "Trash" button disabled from pages list and current edit post - only for custom property page

**Comment by antonkorotkov** [comment]
@SoSeductive I believe these warnings come from here 
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/2276882/38622182-47c7f8de-3dab-11e8-9265-40ea5052aee2.png">

**Comment by fqjony** [comment]
@SoSeductive @Mashenka issue with auto created Properties page still exist. Please check it more. I tested it on rdc with latest version.

**Comment by fqjony** [comment]
@SoSeductive I'm going to setup reddoor develop branch for you to replicate issue which I reported above.

**Comment by fqjony** [comment]
@SoSeductive @Mashenka 

https://github.com/UsabilityDynamics/www.reddoorcompany.com/tree/develop-wp-property
https://www-reddoorcompany-com-develop-wp-property.c.rabbit.ci

Admin creds
Login wpproperty@udx.io
Pass si53syxpy5gq8n94

Let me know if you need some more

**Comment by fqjony** [comment]
**For myself**, after developing need to be sure that is `develop-wp-property` branch and container is removed.

**Comment by Mashenka** [comment]
@ewsopp @fqjony need to recreate this issue in reddoorcompany repository to continue working on it. We can't replicate that issue anywhere else.

 @ewsopp let us know if you want Den working on it still on reddoorcompany project

**Comment by fqjony** [comment]
@Mashenka I'm create another issue at rdc repo
https://github.com/UsabilityDynamics/www.reddoorcompany.com/issues/1971

I'm going to work on it, current issue can stay closed so far.
