### ISSUE TITLE
XMLI. Imported properties must have at least ..., but no more than ... valid images.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#60]
This advanced option from schedule settings doesn't work.

Need to be fixed or deleted from schedule options.

**Comment by pemaxim** [comment]
Done.
There are two separate option right now:
- Imported properties must have at least {number} valid image(s) ( The option is not available for RETS sources since we upload images for this kind of schedule after properties imported ).
- Imported properties must have no more than {number} valid image(s)

http://screencast.com/t/6Ad6BZD6SDQG
