### ISSUE TITLE
Add-on: Renting properties. Availability add on

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#92]
- [ ] Add calendar for free and ordered days. 
- [ ] Add ability to book.
- [ ] Add ability to pay using wp-invoice.
- [ ] Add separate typing for rent and sale properties. Probably it can names Kind of Property, behind the Property type

**Comment by gycsiak** [comment]
Hi,
I also wanted to download such an add-on, because I would like to book and see the History also for renters and renting periods in the past.

I also would like to export the complete list of renting contracts and their period into Excel.

Do you have any updates on this request?

Thank you in advance,

Best regards,

Gyula Csiak

**Comment by Mashenka** [comment]
Hello.

We didn't plan to release that feature in nearest future. But we are available to take custom projects. If you are interested, let us know - https://www.usabilitydynamics.com/hire-us

Regards.
